amcl:
  ros__parameters:
    use_sim_time: True

global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 1.0
      publish_frequency: 1.0
      global_frame: "map"
      robot_base_frame: "base_link"
      use_sim_time: True
      robot_radius: 0.105
      resolution: 0.05
      track_unknown_space: true
      plugins: ["static_layer", "inflation_layer"]
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: true
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 5.0
        inflation_radius: 0.45

local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 5.0
      publish_frequency: 2.0
      global_frame: "odom"
      robot_base_frame: "base_link"
      use_sim_time: True
      rolling_window: true
      width: 3
      height: 3
      resolution: 0.05
      robot_radius: 0.105
      track_unknown_space: true
      plugins: ["static_layer", "inflation_layer"]
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: true
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 5.0
        inflation_radius: 0.35

planner_server:
  ros__parameters:
    expected_planner_frequency: 1.0
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.5
      use_astar: false
      allow_unknown: true

controller_server:
  ros__parameters:
    controller_plugins: ["FollowPath"]
    controller_frequency: 10.0
    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      min_vel_x: 0.0
      max_vel_x: 0.45
      min_vel_y: 0.0
      max_vel_y: 0.0
      min_vel_theta: -1.5
      max_vel_theta: 1.5
      min_speed_xy: 0.0
      max_speed_xy: 0.45
      acc_lim_x: 2.5
      acc_lim_theta: 1.0
      decel_lim_x: -2.5
      decel_lim_theta: -1.5
      vx_samples: 20
      vy_samples: 0
      vtheta_samples: 20
      sim_time: 1.5
      linear_granularity: 0.05
      angular_granularity: 0.01
      xy_goal_tolerance: 0.05
      yaw_goal_tolerance: 0.10
      trans_stopped_velocity: 0.1
      theta_stopped_velocity: 0.1
      short_circuit_trajectory_evaluation: true
      critics: ["PathDist", "GoalDist", "RotateToGoal", "PathAlign", "GoalAlign"]
      PathDist:
        scale: 64.0
      GoalAlign:
        scale: 12.0
      PathAlign:
        scale: 64.0
      GoalDist:
        scale: 64.0
      RotateToGoal:
        scale: 16.0
        slowing_factor: 1.0
        lookahead_time: -1.0
      debug_trajectory_details: false

    goal_checker:
      plugin: "maurice_nav::DynamicGoalChecker"
      time_thresholds: [0.0, 0.30]
      xy_tolerances: [0.05, 0.03]
      yaw_tolerances: [0.10, 0.08]
      linear_vel_tolerances: [1.0, 0.06]
      angular_vel_tolerances: [1.5, 0.20]

    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.5
      movement_time_allowance: 10.0

behavior_server:
  ros__parameters:
    behaviors: ["spin", "backup"]
    spin:
      plugin: "nav2_behaviors/Spin"
    backup:
      plugin: "nav2_behaviors/BackUp"
