# ROS2 parameter file for manipulation behaviors
behavior_manager:
  behavior_names: ["pick_socks", "drop_socks", "drop_paper", "wave", "pick_screwdriver", "pick_motor", "give_object", "open_door", "Test3", "Test4"]
  
  pick_socks:
    file_path: "/home/jetson1/maurice-prod/ros2_ws/src/brain/manipulation/ckpts/socks1wed_socks2wed_filt_merged_20250821_005047_ddp/act_policy_step_135000.pth"
    type: "learned"
    action_dim: 10
    duration: 45.0
    start_pose: [-0.015, -0.399, 1.456, -1.135, -0.023, 0.833]
    end_pose: []
  
  drop_socks:
    file_path: "/home/jetson1/maurice-prod/ros2_ws/src/brain/manipulation/ckpts/dropsocks1wed_dropsocks2wed_merged_20250821_013703_ddp/act_policy_step_140000.pth"
    type: "learned"
    action_dim: 10
    duration: 45.0
    start_pose: []
    end_pose: [1.57693225, -0.6, 1.4772235, -0.73784476, 0.0, 0.0]
  
  drop_paper:
    file_path: ""
    type: "poses"
    steps: 3.0
    poses:
      pose_1: [0.143, -0.434, 0.147, 0.788, 0.060, 0.0]
      pose_2: [0.143, -0.434, 0.147, 0.788, 0.060, 0.701]
      pose_3: [1.57693225, -0.6, 1.4772235, -0.73784476, 0.0, 0.0]
  
  wave:
    file_path: "~/maurice-prod/ros2_ws/src/brain/manipulation/ckpts/Wave/episode_0.h5"
    type: "replay"
    duration: 0.0
    start_pose: []
    end_pose: [1.57693225, -0.6, 1.4772235, -0.73784476, 0.0, 0.0]

  pick_screwdriver:
    file_path: "~/maurice-prod/ros2_ws/src/brain/manipulation/ckpts/screwdriver2_20250817_090517_ddp/act_policy_step_50000.pth"
    type: "learned"
    action_dim: 10
    duration: 45.0
    start_pose: [0.143, -0.434, 0.147, 0.788, 0.060, 0.701]
    end_pose: [1.57693225, -0.8, 1.4772235, -0.73784476, 0.0, 0.0]

  pick_motor:
    file_path: "~/maurice-prod/ros2_ws/src/brain/manipulation/ckpts/motor2_20250817_090016_ddp/act_policy_step_50000.pth"
    type: "learned"
    action_dim: 10
    duration: 45.0
    start_pose: [0.143, -0.434, 0.147, 0.788, 0.060, 0.701]
    end_pose: [1.57693225, -0.8, 1.4772235, -0.73784476, 0.0, 0.0]

  give_object:
    file_path: ""
    type: "poses"
    steps: 4.0
    poses:
      pose_1: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
      pose_2: [1.57693225, -0.8, 1.4772235, -0.73784476, 0.0, 0.0]

  open_door:
    file_path: "/home/jetson1/maurice-prod/ros2_ws/src/brain/manipulation/ckpts/door2_20250826_072615_ddp/act_policy_step_100000.pth"
    type: "learned"
    action_dim: 10
    duration: 45.0
    start_pose: [-0.015, -0.399, 1.456, -1.135, -0.023, 0.0]
    end_pose: [-0.015, -0.399, 1.456, -1.135, -0.023, 0.0]

  Test3:
    file_path: "~/maurice-prod/ros2_ws/src/brain/manipulation/ckpts/Test3/action_only/episode_0.h5"
    type: "replay"
    duration: 0.0
    start_pose: []
    end_pose: [1.57693225, -0.6, 1.4772235, -0.73784476, 0.0, 0.0]

  Test4:
    file_path: "~/maurice-prod/ros2_ws/src/brain/manipulation/ckpts/Test4/action_only/episode_0.h5"
    type: "replay"
    duration: 0.0
    start_pose: []
    end_pose: [1.57693225, -0.6, 1.4772235, -0.73784476, 0.0, 0.0]