version: "3.8"

services:
  innate:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: innate-prod
    environment:
      - INNATE_OS_ROOT=/root/innate-os

    # 2) Or just do a "do-nothing" command so the container doesn't exit
    command: zsh -l

    # 3) Keep container open for interactive usage
    tty: true
    stdin_open: true
