arm:
  ros__parameters:
    device_name: "/dev/ttyACM1"
    baud_rate: 1000000
    control_frequency: 100
    joints: |
      {
          "joint_1": {
              "servo_id": 1,
              "position_limits": {
                  "min": -1.57,
                  "max": 1.57
              },
              "pwm_limits": 885,
              "control_mode": 2
          },
          "joint_2": {
              "servo_id": 2,
              "position_limits": {
                  "min": -0.61,
                  "max": 1.2
              },
              "pwm_limits": 885,
              "control_mode": 2
          },
          "joint_3": {
              "servo_id": 3,
              "position_limits": {
                  "min": -1.57,
                  "max": 1.57
              },
              "pwm_limits": 885,
              "control_mode": 2
          },
          "joint_4": {
              "servo_id": 4,
              "position_limits": {
                  "min": -1.74,
                  "max": 1.74
              },
              "pwm_limits": 885,
              "control_mode": 2
          },
          "joint_5": {
              "servo_id": 5,
              "position_limits": {
                  "min": -1.57,
                  "max": 1.57
              },
              "pwm_limits": 885,
              "control_mode": 2
          },
          "joint_6": {
              "servo_id": 6,
              "position_limits": {
                  "min": -0.0872,
                  "max": 1.0821
              },
              "pwm_limits": 885,
              "current_limit": 100,
              "control_mode": 4
          }
      }
