/**:
  ros__parameters:
    uart:
      port: "/dev/ttyTHS1"
      baud_rate: 115200
      timeout: 0.1
      update_frequency: 30.0
    battery:
      num_cells: 3
      warning_percentage: 20
      critical_percentage: 10
    motion_control:
      max_speed: 0.4
      max_angular_speed: 2.5
      odom_frequency: 30.0
